spring.application.name=TestingApplication

#DB configuration
spring.datasource.url=jdbc:postgresql://postgres-spring-new.crc8q4m8ogwk.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=root
spring.datasource.password=Shikhil-4
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

my.variable=production