spring.application.name=currencyConverterApp
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/currencyConverter
spring.datasource.username=postgres
spring.datasource.password=Shikhil@4

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

currencyService.base.url=https://api.freecurrencyapi.com/v1
currencyService.api.key=fca_live_XJ21tEhxiCV5ePNXuWpr4coLSy20JAI9JEfRMEkM
