spring.application.name=discovery-service

server.port=8761

# discovery-service won't register itself as client of Eureka Server :
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
