spring.application.name=mapstruct

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/understandingMapstruct
spring.datasource.username=postgres
spring.datasource.password=Shikhil@4

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true