spring.application.name=TestingApplication

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/defaultCaching
spring.datasource.username=postgres
spring.datasource.password=Shikhil@4
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# redis configuration (Localhost)
#spring.cache.type=redis
#spring.data.redis.host=redis-12973.crce217.ap-south-1-1.ec2.cloud.redislabs.com
#spring.data.redis.port=12973

# redis configuration (Cloud Server)
spring.cache.type=redis
spring.data.redis.host=redis-12973.crce217.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=12973
spring.data.redis.password=MDHWcMwMRdBEwus3haHPW0IGrLQdZ5J1
#spring.data.redis.ssl.enabled=false